#!/bin/bash
# mac-build.sh takes the team from the runner's config; the project
# generator takes it from CHIRON_TEAM_ID. A build whose project has no
# team fails to sign at the archive, so the config's team must reach the
# generated project. Needs xcodegen (a Mac with Homebrew).
set -euo pipefail
HERE="$(cd "$(dirname "$0")" && pwd)"
T=$(mktemp -d); trap 'rm -rf "$T"' EXIT
export HOME="$T/home"
mkdir -p "$HOME/.config/chiron-runner" "$T/repo/scripts" "$T/repo/ipad-app"
printf 'team_id = TEAM123456\nbuilds_url = https://example.invalid/builds\n' > "$HOME/.config/chiron-runner/config"
cp "$HERE/mac-build.sh" "$T/repo/scripts/"
cat > "$T/repo/ipad-app/project.yml" <<'YML'
name: Probe
targets:
  Probe:
    type: tool
    platform: macOS
    settings:
      DEVELOPMENT_TEAM: ${CHIRON_TEAM_ID}
YML
cd "$T/repo" && git init -q && git add -A && git -c user.email=t@t -c user.name=t commit -qm probe
unset CHIRON_TEAM_ID
# The build stops at the unit tests (the probe has none); the project is
# generated by then.
"$T/repo/scripts/mac-build.sh" HEAD >/dev/null 2>&1 || true
if grep -q "DEVELOPMENT_TEAM = TEAM123456" "$T/repo/ipad-app/Probe.xcodeproj/project.pbxproj" 2>/dev/null; then
  echo "mac-build: 1 passed"
else
  echo "FAIL: the config's team_id did not reach the generated project" >&2
  exit 1
fi
